#
# CIter - C library for lazily-evaluated iterators.
# Copyright (C) 2024  Kian Kasad <kian@kasad.com>
#
# This file is part of CIter.
#
# CIter is free software: you can redistribute it and/or modify it under the terms
# of the GNU Lesser General Public License as published by the Free Software
# Foundation, version 3 of the License.
#
# CIter is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with CIter. If not, see <https://www.gnu.org/licenses/>.
#

name: Build & test

on:
  push:
    paths:
      - "src/**"
      - "examples/**"
      - "Makefile"
      - ".github/workflows/test.yml"
  pull_request:
    branches:
      - master
      - "release/*"

env:
  MAKEFLAGS: -j

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Test
        run: ./examples/run_all.sh
